#!/usr/bin/env bash
# SPDX-License-Identifier: GPL-2.0-only
# SPDX-FileCopyrightText: 2026 Anirban Phukan
# Build the reference-oracle matrix used for the M1 noise-floor and instrumentation-equivalence tests.
#   usage: tools/build_reference_matrix.sh <pristine-lammps-tree> <out-root> [variant ...]
# Layout: <out-root>/<variant>/{build,install}  (instrumented variants also keep <out-root>/<variant>/work).
# Variants (compiler / flags -- the first four have a stock and an instrumented twin, the rest are stock-only probes):
#   gcc          default g++ (-O3 from CMake Release; no FMA on baseline x86-64)
#   clang        clang++
#   gcc-native   g++ -march=native -ffp-contract=fast   (FMA contraction ON: stresses rounding differences)
#   clang-native clang++ -march=native -ffp-contract=fast
#   gcc-O0 / gcc-O2-nofma   g++ at -O0 / at -O2 with -ffp-contract=off  (stock only)
#   mpi            OpenMPI (mpicxx.openmpi; override MPI_CXX/MPI_CC), BUILD_MPI=on (Ubuntu's MPICH is PMIx-only and starts singletons in the sandbox): run with 1/2/4 ranks (reduction-order noise; stock only)
#   kokkos-serial  PKG_KOKKOS with the Serial backend: `pair_style reaxff/kk` in double precision (stock only)
# Existing variants (install/bin/lmp present) are skipped, so the script is idempotent.
# NOTE: do not edit this file while it is running (bash reads scripts incrementally).
set -uo pipefail
src="${1:?pristine lammps tree}"; out="${2:?out root}"; shift 2
here="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
all=(gcc clang gcc-native clang-native)
# stock-only variants (noise-floor probes; no instrumented twin): optimisation level, explicit FMA off, MPI, Kokkos
stock_only=(gcc-O0 gcc-O2-nofma mpi kokkos-serial)
variants=("$@"); [[ ${#variants[@]} -gt 0 ]] || variants=("${all[@]}" "${stock_only[@]}")
rc=0
for v in "${variants[@]}"; do
  kinds=(stock inst)
  for so in "${stock_only[@]}"; do [[ "$so" == "$v" ]] && kinds=(stock); done
  for kind in "${kinds[@]}"; do
    d="$out/$kind-$v"
    if [[ -x "$d/install/bin/lmp" ]]; then echo "[skip] $kind-$v"; continue; fi
    mkdir -p "$d"
    case "$v" in
      gcc) xa=() ;;
      clang) xa=(-DCMAKE_CXX_COMPILER=clang++ -DCMAKE_C_COMPILER=clang) ;;
      gcc-native) xa=("-DCMAKE_CXX_FLAGS=-march=native -ffp-contract=fast") ;;
      clang-native) xa=(-DCMAKE_CXX_COMPILER=clang++ -DCMAKE_C_COMPILER=clang "-DCMAKE_CXX_FLAGS=-march=native -ffp-contract=fast") ;;
      gcc-O0) xa=("-DCMAKE_CXX_FLAGS_RELEASE=-O0") ;;
      gcc-O2-nofma) xa=("-DCMAKE_CXX_FLAGS_RELEASE=-O2" "-DCMAKE_CXX_FLAGS=-ffp-contract=off") ;;
      mpi) xa=(-DBUILD_MPI=on "-DCMAKE_CXX_COMPILER=${MPI_CXX:-mpicxx.openmpi}" "-DCMAKE_C_COMPILER=${MPI_CC:-mpicc.openmpi}") ;;
      kokkos-serial) xa=(-DPKG_KOKKOS=on -DKokkos_ENABLE_SERIAL=on -DKokkos_ENABLE_OPENMP=off) ;;
      *) echo "unknown variant $v" >&2; exit 2 ;;
    esac
    echo "[build] $kind-$v"
    if [[ "$kind" == stock ]]; then
      JOBS="${JOBS:-4}" "$here/tools/build_lammps_reference.sh" "$src" "$d/build" "$d/install" "${xa[@]}" > "$d/build.log" 2>&1
    else
      rm -rf "$d/work"
      JOBS="${JOBS:-4}" "$here/tools/build_lammps_instrumented.sh" "$src" "$d/work" "$d/build" "$d/install" "${xa[@]}" > "$d/build.log" 2>&1
    fi
    r=$?; echo "[done] $kind-$v rc=$r"; [[ $r -eq 0 ]] || rc=1
  done
done
exit $rc
